import { z } from "zod";
import type { ServiceTitanClient } from "../../client.js";
import type { ToolRegistry } from "../../registry.js";
import { toolResult, toolError, buildParams } from "../../utils.js";

const exportSchema = {
  from: z.string().optional().describe("Continuation token or date string for incremental export"),
  includeRecentChanges: z.boolean().optional().describe("Include recent changes not yet committed"),
};

function registerExportTool(
  registry: ToolRegistry,
  client: ServiceTitanClient,
  name: string,
  description: string,
  path: string,
  schema: Record<string, z.ZodType> = exportSchema,
) {
  registry.register({
    name,
    domain: "export",
    operation: "read",
    description,
    schema,
    handler: async (params: unknown) => {
      try {
        const data = await client.get(path, buildParams(z.object(schema).parse(params)));
        return toolResult(data);
      } catch (error: unknown) {
        return toolError(error);
      }
    },
  });
}

export function registerExportTools(client: ServiceTitanClient, registry: ToolRegistry) {
  // Accounting exports
  registerExportTool(registry, client, "export_invoices", "Read the incremental invoices export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/invoices");
  registerExportTool(registry, client, "export_invoice_items", "Read the incremental invoice items export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/invoice-items");
  registerExportTool(registry, client, "export_invoice_templates", "Read the incremental invoice templates export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/invoice-templates");
  registerExportTool(registry, client, "export_payments", "Read the incremental payments export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/payments");
  registerExportTool(registry, client, "export_adjustments", "Read the incremental adjustments export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/adjustments");
  registerExportTool(registry, client, "export_inventory_bills", "Read the incremental inventory bills export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/inventory-bills");
  registerExportTool(registry, client, "export_payroll_adjustments", "Read the incremental payroll adjustments export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/payroll-adjustments");

  // CRM exports
  registerExportTool(registry, client, "export_customers", "Read the incremental customers export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/customers");
  registerExportTool(registry, client, "export_customers_contacts", "Read the incremental customers contacts export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/customers/contacts");
  registerExportTool(registry, client, "export_locations_contacts", "Read the incremental locations contacts export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/locations/contacts");
  registerExportTool(registry, client, "export_contacts", "Export contacts", "/tenant/{tenant}/export/contacts");
  registerExportTool(registry, client, "export_locations", "Read the incremental locations export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/locations");
  registerExportTool(registry, client, "export_leads", "Read the incremental leads export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/leads");
  registerExportTool(registry, client, "export_bookings", "Read the incremental bookings export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/bookings");

  // Dispatch exports
  registerExportTool(registry, client, "export_jobs", "Read the incremental jobs export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/jobs");
  registerExportTool(registry, client, "export_job_notes", "Read the incremental job notes export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/job-notes");
  registerExportTool(registry, client, "export_job_history", "Read the incremental job history export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/job-history");
  registerExportTool(registry, client, "export_job_canceled_logs", "Read the incremental job canceled logs export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/job-canceled-logs");
  registerExportTool(registry, client, "export_job_splits", "Read the incremental job splits export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/jobs/splits");
  registerExportTool(registry, client, "export_job_cancel_reasons", "Export job cancel reasons", "/tenant/{tenant}/export/job-cancel-reasons");
  registerExportTool(registry, client, "export_appointments", "Read the incremental appointments export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/appointments");
  registerExportTool(registry, client, "export_appointment_assignments", "Read the incremental appointment assignments export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/appointment-assignments");
  registerExportTool(registry, client, "export_projects", "Read the incremental projects export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/projects");
  registerExportTool(registry, client, "export_project_notes", "Read the incremental project notes export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/project-notes");
  registerExportTool(registry, client, "export_installed_equipment", "Read the incremental installed equipment export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/installed-equipment");

  // People exports
  registerExportTool(registry, client, "export_technicians", "Read the incremental technicians export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/technicians");
  registerExportTool(registry, client, "export_employees", "Read the incremental employee export feed for cross-domain bulk synchronization. This is the same feed as people_employees_export; use whichever name is available and do not fetch both. Continue immediately with continueFrom while hasMore is true; when false, retain it and wait before polling again. includeRecentChanges may repeat records.", "/tenant/{tenant}/export/employees");

  // Pricebook exports
  registerExportTool(registry, client, "export_services", "Read the incremental services export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/services");
  registerExportTool(registry, client, "export_materials", "Read the incremental materials export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/materials");
  registerExportTool(registry, client, "export_equipment", "Read the incremental equipment export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/equipment");

  // Membership exports
  registerExportTool(registry, client, "export_memberships", "Read the incremental memberships export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/memberships");
  registerExportTool(registry, client, "export_membership_types", "Read the incremental membership types export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/membership-types");
  registerExportTool(registry, client, "export_membership_status_changes", "Read the incremental membership status changes export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/membership-status-changes");
  registerExportTool(registry, client, "export_service_agreements", "Read the incremental service agreements export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/service-agreements");
  registerExportTool(registry, client, "export_recurring_service_types", "Read the incremental recurring service types export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/recurring-service-types");
  registerExportTool(registry, client, "export_location_recurring_services", "Export location recurring services", "/tenant/{tenant}/export/location-recurring-services");
  registerExportTool(registry, client, "export_location_recurring_service_events", "Export location recurring service events", "/tenant/{tenant}/export/location-recurring-service-events");

  // Marketing exports
  registerExportTool(registry, client, "export_calls", "Read the incremental calls export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/calls");

  // Payroll exports
  registerExportTool(registry, client, "export_timesheets", "Export timesheets", "/tenant/{tenant}/export/timesheets");
  registerExportTool(registry, client, "export_timesheet_codes", "Read the incremental timesheet codes export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/timesheet-codes");
  registerExportTool(registry, client, "export_gross_pay_items", "Read the incremental gross pay items export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/gross-pay-items");
  registerExportTool(registry, client, "export_payroll_settings", "Read the incremental payroll settings export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/payroll-settings");

  // Settings exports
  registerExportTool(registry, client, "export_activities", "Read the incremental timesheet-activity export feed for cross-domain bulk synchronization. This is the same feed as settings_activities_export; use whichever name is available and do not fetch both. Continue immediately with continueFrom while hasMore is true; when false, retain it and wait before polling again. includeRecentChanges may repeat records.", "/tenant/{tenant}/export/activities");
  registerExportTool(registry, client, "export_activity_codes", "Read the incremental activity-code export feed for cross-domain bulk synchronization. This is the same feed as settings_activity_codes_export; use whichever name is available and do not fetch both. Continue immediately with continueFrom while hasMore is true; when false, retain it and wait before polling again. includeRecentChanges may repeat records.", "/tenant/{tenant}/export/activity-codes");
  registerExportTool(registry, client, "export_business_units", "Read the incremental business units export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/business-units");
  registerExportTool(registry, client, "export_tag_types", "Read the incremental tag-type export feed for cross-domain bulk synchronization. This is the same feed as settings_tag_types_export; use whichever name is available and do not fetch both. Continue immediately with continueFrom while hasMore is true; when false, retain it and wait before polling again. includeRecentChanges may repeat records.", "/tenant/{tenant}/export/tag-types");

  // Inventory exports
  registerExportTool(registry, client, "export_purchase_orders", "Read the incremental purchase orders export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/purchase-orders");
  registerExportTool(registry, client, "export_returns", "Read the incremental returns export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/returns");
  registerExportTool(registry, client, "export_transfers", "Read the incremental transfers export feed for bulk synchronization. Start with a date or omit from to start at the beginning of the feed, continue immediately with continueFrom while hasMore is true, and when false retain it and wait before polling again. includeRecentChanges may return records sooner but can repeat them.", "/tenant/{tenant}/export/transfers");
}
